name: Update Submodule and Deploy to Vercel

on:
  repository_dispatch:
    types: [content_update]

jobs:
  update_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main repository
      uses: actions/checkout@v2
      with:
        submodules: true  

    - name: Update submodule to latest commit
      run: |
        # Fetch the latest commits from the submodule
        cd src/content
        git fetch
        git checkout main  # Replace 'main' with the branch you want to track
        git pull origin main  # Update the submodule to the latest commit
        cd ../..  # Return to the main repository directory
        git add src/content
        git commit -m "Update submodule to latest version" || echo "No changes to commit"
        
    - name: Push updated submodule
      run: |
        git push origin main
